# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_taxt',
            new_name='article_text',
        ),
    ]
